### ISSUE TITLE
Use OpenIddict as OpenID Connect compatible authentication framework

### ISSUE THREAD

**Issue by xperiandri** [alex-kukhtin/A2v10.Core#1]
Built-in ASP.NET Core JWT token code is insecure non-production-ready.
In my opinion the best solution for .NET is [OpenIddict](https://github.com/openiddict/) library.

The only alternative IdentityServer is not free now and is much worse written and hard to understand and incorporate into your app.

**Comment by alex-kukhtin** [comment]
Can I get more detailed information? 
Why is this not production-ready?

**Comment by xperiandri** [comment]
Because no one validates a JWT token on the client-side unless it uses an industry-standard JWT client library that does that itself by default.
I have seen a lot of projects with custom JWT and non of them had token validation on the client-side.

**Comment by xperiandri** [comment]
And why invent the wheel if OpenID Connect does everything needed!

**Comment by alex-kukhtin** [comment]
Tell me more from here. What is the logic for checking the token on the client? What can be checked there? It's a token.

**Comment by alex-kukhtin** [comment]
OpenID connect is also supported.

**Comment by xperiandri** [comment]
> OpenID connect is also supported.

Could you point me where to configure it?

**Comment by xperiandri** [comment]
> Tell me more from here. What is the logic for checking the token on the client? What can be checked there? It's a token.

What if I intercept the connection and pretend like your server. I will create a token for your client, and it will send all the information to me while my server will work as a proxy.
If a client does not validate the token it will not check if the correct server signed the token.
