### ISSUE TITLE
Use Orchard Core Framework for multi-tenancy and modularity

### ISSUE THREAD

**Issue by xperiandri** [alex-kukhtin/A2v10.Core#2]
[Orcharc Core CMS](https://github.com/OrchardCMS/OrchardCore/) already implements in-process multi-tenancy and modularity.
You can use an infrastructure-only piece of Orchard Core named Orchard Core Framework to get only multi-tenancy and modularity without all the CMS-related add-ons.

**Comment by alex-kukhtin** [comment]
In my humble opinion, it's just yet another CMS.
What is the meaning of integrating it into the platform?

**Comment by xperiandri** [comment]
[This piece](https://github.com/OrchardCMS/OrchardCore/tree/main/src/OrchardCore.Modules) is CRM but [this one](https://github.com/OrchardCMS/OrchardCore/tree/main/src/OrchardCore) is core framework.

You can reference https://www.nuget.org/packages/OrchardCore.Application.Targets/ for minimal functionality:
1. multi-tenancy (they create a separate DI container scope per tenant with the ability to load different modules)
2. modularity (just place a Startup derived class into your ASP.NET Core library and reference it)

Or https://www.nuget.org/packages/OrchardCore.Application.Mvc.Targets/ with UI stuff support

**Comment by xperiandri** [comment]
I can show you a sample if you are interested in this.
The most useful idea, in my opinion, of Orchard Core Framework, is the ability to host several "instances" of the ASP.NET Core app inside a single process and enable/disable modules on the fly per instance.
