### ISSUE TITLE
Як отримати в шаблоні всі фільтри CollectionView?

### ISSUE THREAD

**Issue by bohdan-bats-bs** [alex-kukhtin/A2v10.Core#5]
Намагався наступним чином це зробити за допомогою TRoot.Collection, яка прив'язана до властивості CollectionView.ItemsSource:
`root.Collection.$ModelInfo.Filter`
Але чомусь воно повертає лише перший фільтр в FilterDescription, а не усі

**Comment by alex-kukhtin** [comment]
Filter ЗАВЖДИ один.
Подивись всередину

**Comment by bohdan-bats-bs** [comment]
Я всередину й дивлюсь. Лише перший фільтр там є

**Comment by bohdan-bats-bs** [comment]
`console.dir(this.Collection.$ModelInfo.Filter);`
Отримую:
![image](https://user-images.githubusercontent.com/118750925/220583441-b9760a60-e3f9-4ab0-90e3-b36f459c2603.png)
В .xaml:
`<Page.CollectionView>
        <CollectionView ItemsSource="{Bind Collection}"
                                   RunAt="Server">
            <CollectionView.Filter>
                <FilterDescription>

                    <FilterItem Property="Fragment"
                                DataType="String" />

                    <FilterItem Property="Manager"
                                DataType="Object" />

                    <FilterItem Property="ShowBasket"
                                DataType="Boolean" />

                </FilterDescription>
            </CollectionView.Filter>
        </CollectionView>
</Page.CollectionView>`

**Comment by alex-kukhtin** [comment]
Ти не повернув фільтр в моделі.
Те що в xaml  - прив'язує до існуючого, якщо є. Якщо нема - нічого не відбувається.
Щось типа такого:

[!ocuments.ManagerId!Filter] = @Manager, [!Documents.Manager.Name!Filter] = @ManagerName
