### ISSUE TITLE
Робота з jobs в шедулері

### ISSUE THREAD

**Issue by Seeges** [alex-kukhtin/A2v10.Core#9]
Зараз для реєстрації обробника використовується такий синтаксис:
![image](https://github.com/alex-kukhtin/A2v10/assets/23618821/955d8c4d-44f4-42cd-ba2e-bb6d85d35f95)
і в файлі **appsetting.json** ми описуємо jobs так:
![image](https://github.com/alex-kukhtin/A2v10/assets/23618821/de13c4ee-4cc4-48ea-bda8-4bea332189e6)
Насправді це якась фігня, бо фактично зареєстровано в системі один обробник, але під двома різними псевдонімами "ExecuteSqlSample1" та "ExecuteSqlSample2". Це додає плутанини та збільшує верогідність помилки.

Але при цьому поле "Handler" це не імя обробника, а якийсь зайвий пов'язуючий елемент.

Я би змінив підхід. Ми можемо у файлі **appsetting.json** одразу вказувати імя класу обробника, наприклад:
![image](https://github.com/alex-kukhtin/A2v10/assets/23618821/df644880-c5ff-44ee-be53-62327fcf9244)
Тоді при реєстрації обробника не потрібно вказувати ніяких псевдоімен:
![image](https://github.com/alex-kukhtin/A2v10/assets/23618821/c069f554-2585-49b9-83cd-17934a6a903b)
Тобто просто реєструємо обробник і все.
Тоді потрібно переробити і метод FindHandler() і шукати Handler не по псевдоніму, а по імені класа-обробника. Метод цей:
![image](https://github.com/alex-kukhtin/A2v10/assets/23618821/992dd341-6d66-4537-ba86-628902a88a77)

**Comment by alex-kukhtin** [comment]
Мабуть додам RegisterHandler<T>(). А тип буде братися з typeof(T).FullName. 
Тільки потрібно буде вказувати повне ім'я типу
{
  "Handler": "A2v10.Scheduling.ExecuteSqlJobHandler"
}

Тоді буде працювати і так і так, кому як зручно.

**Comment by Seeges** [comment]
Якщо залишити варіант RegisterHandler<T>(String name), то виникає багато питань та плутанини. Наприклад я проводив експерименти і додав такий код:
'''c#
factory.RegisterJobHandler<ExecuteSqlJobHandler>("ExecuteSqlJobHandler1")
.RegisterJobHandler<ExecuteSqlJobHandler>("ExecuteSqlJobHandler2")
```
Тут порушена логіка, бо під різнимиі псевдонімами буде визиватися один і тойже хендлер ExecuteSqlJobHandler. Тобто код працює, але це неправильно.
Також я продував і такий варіант:

**Comment by alex-kukhtin** [comment]
Взагалі не бачу проблеми.  Є куча кейсів коли мені може бути потрібен один хендлер, але, наприклад, з різними налаштуваннями. Це на майбутні розширення.
